name: Python CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: print message
        run: echo "fisrt activation github action"

      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: check reposotory
        run: ls -la
