name: manual CI

on:
  workflow_dispatch:
    inputs:
      enviromments:
        description: "choose"
        required: true
        type: choice
        options:
          - prod
          - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: print message on the terminal
        run: echo "running the task on ${{ inputs.enviromments }}"
